sudo: false
language: python
python:
  - "2.7"
  - "pypy"
cache:
  directories:
    - $HOME/.pip-cache/
install:
  - pip install -e git+git://github.com/onaio/onapie.git#egg=onapie
  - pip install --upgrade pip --cache-dir $HOME/.pip-cache/
  - pip install coveralls --cache-dir $HOME/.pip-cache/
  - pip install flake8 --cache-dir $HOME/.pip-cache/
  - pip install -r requirements-dev.txt --cache-dir $HOME/.pip-cache/
  - pip install -e . --cache-dir $HOME/.pip-cache/
  - echo "ONAPIE_ACCESS_TOKEN = 'foo'" >> malaria24/settings/local.py
  - echo "VUMI_GO_ACCOUNT_KEY = 'VUMI_GO_ACCOUNT_KEY'" >> malaria24/settings/local.py
  - echo "VUMI_GO_API_TOKEN = 'VUMI_GO_API_TOKEN'" >> malaria24/settings/local.py
  - echo "VUMI_GO_CONVERSATION_KEY = 'VUMI_GO_CONVERSATION_KEY'" >> malaria24/settings/local.py

script:
  - flake8 malaria24
  - py.test --cov=malaria24 --cov-report=term
after_success:
  - coveralls
deploy:
  provider: pypi
  user: Praekelt
  password:
    # NOTE: See http://docs.travis-ci.com/user/encryption-keys/ for more info.
    secure: "insert encrypted pypi password here"
  on:
    tags: true
    all_branches: true
