language: python
python:
  - "2.7"

cache:
  - pip

before_install:
  - pip install --upgrade pip

install:
  - pip install -e git+git://github.com/onaio/onapie.git#egg=onapie
  - pip install coveralls
  - pip install flake8
  - pip install -r requirements-dev.txt
  - pip install -e .

script:
  - flake8 malaria24

   # check for model changes not reflected in a migration
  - python manage.py makemigrations --dry-run | grep 'No changes detected' || (echo 'There are changes which require migrations.' && exit 1)
  - py.test
after_success:
  - coveralls

jobs:
  include:
    - stage: test
    - stage: docker
      services: [docker]
      dist: xenial
      python: "3.7"
      env:
        - IMAGE_NAME=praekeltfoundation/malariaconnect
        - REGISTRY_USER=praekeltorgdeploy
        - secure: "NCYJda292/G3brt2E7x9wDLM2UsdcwSl0Q+6m+TtcGyJSCt7aSVW8wR2ts5+9nu2THG0h/aotKVCfUX2jycZdT5AX72pLpm48sosVP1X5Inwt16+FfaSZPwr7RvIQEQdfPbJUmUvZKCQ6EfGRAppcBDc46s+br2VKwbmZSHkMTua8qUwvayIYOoOFQSUYoWuIT3IiwxwSHTyHpOsKS7PkZ+boPWV4jcO2SIl2rfJzvI9Hx/GCqWNpngqCyP79DlDvFu+or/+D+HlvkfGhg4CmriewLGOHP+l3nxDsXDQO4OoYfZoxBs8e9TgeeuC+VhyFUqPf21OfOQVvh8M/aCCy/hmtPdRGFtcqwwK+sjIeC4EjRMKhS92XJeypdh+umlJNP1dMlxPiky8i/Rdl23cBX4tuVU5knTzMLB08S8eFoCUGYOKOUN2WO36J4b5GzbzVKoJRsWeNW1IoCad3t57+OrCI3db+HYCqxsuQS/xQsCxjmycYmtkAiRIMWdFZGXHqPg/IShTKlvigQzJj11D63Z4ujVA6qdPi2zdrUg6jETtjq5plmd9jUaWzLV72DkonckLzkAWvM6WpYPOlGN3qrWEWPTZaGpE2+1Rw1Z40aFaxb0nlE8/POOwMdJA+OZCAkUl6sNffCPWYdK1reSN4BxqqfLI7rEp222bGWXAaa8="

      install:
        - pip install seaworthy[pytest]

      before_script:
        - docker pull "$IMAGE_NAME" || true


      script:
        - docker build --pull --cache-from "$IMAGE_NAME" -t .
        - cd seaworthy/
        - pytest tests.py

      before_deploy:
        - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
        - pip install docker-ci-deploy==0.3.0

      deploy:
        provider: script
        script: dcd -V $(git rev-parse --short HEAD) -L "$IMAGE_NAME"
        on:
          branch: develop
      - secure: XYnl1GQpsMDZsktGcHQLzfSxpsOyJeCDAbV0fOYeMXsKQgVO80S1ZyNE5G8uOcEojtETDUI0jNvi5am5Y4wQ7BQqJPsIt0avXekbLs0FVTN2ZvpgKV+NacBHwsaW8V68L2NMVyx47TRXFguaigjzWG+QX/8XP56LUFUDUomWHnEc8yP6L3A2KK2yVC8WmeuGk6y1X1SqEvhUTMGvs6fUJn4CgyHuBP3NwFRcXF7wQWQElaaw6UTmbxHtwTrAdJjyf9lUmOPHboGUThe0YnS2T5cQc6Yf9tIH94ExyXSVAIfJUU3TTXkMxKCgYZxhvLKaizqp3vxkPJz6crr2fVJXJQ/9TRNPltbdH5Z79osb/QSzgoufFsxR+w9wbEuzFgx+orzaDxW578yWtKLjt/qqANDUT+Xx+Cgg49RzfVl6Vc16wr3jQRKcGXbzCtaDWjrmFXjBgQvWCGd+seVdT3Cw5tvi5tigzlWR1kLNRHoMRW3MuJFCyYQ27VpGEAUUo5mlj3vbmMA/caqZKaEdxYlgDN8Z+YzM646FeDwCmF4zGL0ClSvQZmrMTjRtaBPiMM6j6Wo9g5UxTFLdajjIrFID+VEwb26nAGQliWHY6YaT8H6ENEcjhYaqW21sRJyHTH5SBxaKXTD5V5TTAgqFinb2ZwJDavSABHQj8ESnB2GxugY=
